### ISSUE TITLE
Problems with Oracle 12.1.0

### ISSUE THREAD

**Issue by roger-cazangi** [CharcoalUchiha/Hangfire.Oracle#1]
Problems found using OracleClient10Managed with Oracle 12.1.0:

1- Immediately after tables are created, first try of insertion on table Dual fails with error ORA-08177.
2- An exception is raised when trying to use transaction isolation "ReadUncommited"
3- JobQueues queries doesn't return data when queue's names contains upper case characters.
4- Statistics query doesn't return correct counts.

I have fixed all problems listed above, can I open a Pull request with my changes?

**Comment by CharcoalUchiha** [comment]
Hello Roger,

Sorry for the late reply; I did not get a notification for this issue.

This project was a refactor of the original [Hangfire w/Oracle Support](https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage) project.  I just downloaded the original code, fixed the issues I was having, and created a brand new project:  Hangfire.Oracle  

I will be removing this project in a couple of weeks, on July 18th.  I'm not sure if doing so will remove your fork or not.  Please download your fork's code, and create a new project.  I apologize for any inconveniences.
